//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.17 at 02:56:13 PM MSK 
//


package com.wklab.itiv422.soap.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wklab.itiv422.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wklab.itiv422.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Birthday }
     * 
     */
    public Birthday createBirthday() {
        return new Birthday();
    }

    /**
     * Create an instance of {@link GetFriendsByPersonAndYearRequest }
     * 
     */
    public GetFriendsByPersonAndYearRequest createGetFriendsByPersonAndYearRequest() {
        return new GetFriendsByPersonAndYearRequest();
    }

    /**
     * Create an instance of {@link GetFriendsByPersonAndYearResponse }
     * 
     */
    public GetFriendsByPersonAndYearResponse createGetFriendsByPersonAndYearResponse() {
        return new GetFriendsByPersonAndYearResponse();
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPersonDto() {
        return new PersonDto();
    }

}
