//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.17 at 02:56:13 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://itiv422.wklab.com/soap/dto", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wklab.itiv422.soap.dto;
